version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - C:/Users/akamb/Documents/Akbot git/akbot-public:/usr/app/src
